In [11]:
import numpy as np


In [12]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [14]:
# Вычисляем среднее значение и стандартное отклонение
mean_value = np.mean(matrix)
print("Ср. значение: ")
print(mean_value)
std_deviation = np.std(matrix)
print("\n")
print("Стандартное отклонение:")
print(std_deviation)

# Нормализация матрицы
normalized_matrix = (matrix - mean_value) / std_deviation

print("\n")
print("Нормализированная матрица:")
print(normalized_matrix)

Ср. значение: 
5.0


Стандартное отклонение:
2.581988897471611


Нормализированная матрица:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
